package com.carsplatform.util;

import com.carsplatform.filehandler.FileHandler;
import jakarta.servlet.ServletContextEvent;
import jakarta.servlet.ServletContextListener;
import jakarta.servlet.annotation.WebListener;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

@WebListener
public class DataDirectoryListener implements ServletContextListener {

    @Override
    public void contextInitialized(ServletContextEvent sce) {
        // app.properties is generated by Maven at build time with resource filtering.
        // data.dir is replaced with the absolute path to src/main/webapp/data on
        // THIS machine, so it works regardless of where Tomcat is installed.
        String dataDir = readDataDirFromProperties(sce);

        if (dataDir != null) {
            Path path = Paths.get(dataDir.trim());
            if (Files.isDirectory(path)) {
                FileHandler.setDataDirectory(path.toString());
                sce.getServletContext().log("DataDirectoryListener: data directory = " + path);
                return;
            }
        }

        // Fallback: use the deployed webapp folder (target/car-rental-platform/data)
        String fallback = sce.getServletContext().getRealPath("/data");
        if (fallback != null) {
            FileHandler.setDataDirectory(fallback);
            sce.getServletContext().log("DataDirectoryListener: data directory (fallback) = " + fallback);
        }
    }

    private String readDataDirFromProperties(ServletContextEvent sce) {
        try (InputStream in = sce.getServletContext()
                .getResourceAsStream("/WEB-INF/classes/app.properties")) {
            if (in == null) return null;
            Properties props = new Properties();
            props.load(in);
            return props.getProperty("data.dir");
        } catch (IOException e) {
            sce.getServletContext().log("DataDirectoryListener: could not read app.properties", e);
            return null;
        }
    }
}
